version: '3.8'

services:
  detection-service:
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia  # Required for GPU access
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./model:/app/model
      - ./data:/app/data
      - ./output:/app/output
    ports:
      - "8000:8000"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  web-interface:  # Optional - if you want a web interface
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html
      - ./output:/usr/share/nginx/html/output
    depends_on:
      - detection-service